### ISSUE TITLE
[Android][BottomBarNavigation] No pressed state for BottomBarNavigation

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Material#103]
## Current behavior

No pressed state for BottomBarNavigation
![no presed state](https://user-images.githubusercontent.com/49959074/83447308-3eee4c00-a41e-11ea-9a68-3c03dcaead7e.png)

## How to reproduce it (as minimally and precisely as possible)

1. Launch app
2. Select BottomBarNavigation from burger menu
3. Tap an item from the BottomBarNavigation
4. Notice no pressed state

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] UWP

**Comment by Massimo37** [comment]
Will be fixed when the Ripple control is fixed on android.

**Comment by StewartPolsky** [comment]
Unable to reproduce issue
