### ISSUE TITLE
[UWP][BottomBarNavigation] Pressed state does not remain if pressed a second time, pressed state also removed by hover over state

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Material#107]
## Current behavior

![Uno Material BBN pressed state](https://user-images.githubusercontent.com/49959074/83452319-824cb880-a426-11ea-9996-9ef31fd82941.gif)

## Expected behavior

Pressed state should remain if pressed a second time

## How to reproduce it (as minimally and precisely as possible)

1. Launch UWP app
2. Select BottomBarNavigation from burger menu
3. Click 'Search'
4. Click 'Search' again
5. Notice that there is no longer a pressed state

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] UWP

**Comment by Massimo37** [comment]
Fixed. @StewartPolsky to review.

**Comment by StewartPolsky** [comment]
Fix verified
