### ISSUE TITLE
ToggleSwitch

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/Uno.Material#11]

**Comment by MatFillion** [comment]
There's a small issue on android. The circle has no elevation so it looks odd when white.

![image](https://user-images.githubusercontent.com/7029537/81597733-2d240680-9394-11ea-9107-6fdc42bd7e39.png)

**Comment by MatFillion** [comment]
Seems the style is off on UWP Dark theme.

![image](https://user-images.githubusercontent.com/7029537/82632465-4b74d800-9bc6-11ea-8716-0dafc049211f.png)

**Comment by NicolasChampagne** [comment]
The workaround for #41 causes this, once latest uno is merged and workaround is removed, it should work.

**Comment by MatFillion** [comment]
Once #100 is merged we can remove the workarounds

**Comment by StewartPolsky** [comment]
Fix verified
