### ISSUE TITLE
ComboBox

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/Uno.Material#12]

**Comment by StewartPolsky** [comment]
On WASM, selected item in combo box does not show proper selected state.
**Current Results**
![Uno Material ComboBox](https://user-images.githubusercontent.com/49959074/82474424-0acb7080-9a99-11ea-88f8-291f1bc1265d.png)

**Expected Results:**
![Uno Material ComboBox good](https://user-images.githubusercontent.com/49959074/82474439-0f902480-9a99-11ea-8cf5-a7b165e93c93.png)

**Comment by StewartPolsky** [comment]
On Android, select an item from the combo box (ex. a), go back and change selection to another item (ex. b), open combo box a third time to make another selection. Notice there is part of an outline.

![Uno Material_ComboBox](https://user-images.githubusercontent.com/49959074/82475004-d310f880-9a99-11ea-80ad-b995976685e3.gif)

**Comment by MatFillion** [comment]
Closing, we will keep the uno issue instead.
