### ISSUE TITLE
 Uno.Material NuGet is not available at Nuget package manager.

### ISSUE THREAD

**Issue by avikeid2007** [unoplatform/Uno.Material#162]
## On which page?
https://github.com/unoplatform/Uno.Material
## What's wrong?
Getting Started=>Step 1. Install the NuGet package, Uno.Material - This **NuGet is not available at Nuget package manager.** [https://www.nuget.org/packages?q=Uno.Material](https://www.nuget.org/packages?q=Uno.Material)
## Any feedback?
Please publish Uno.Material NuGet, It is difficult to maintain using DLL.

**Comment by MatFillion** [comment]
@avikeid2007 You are correct the readme is misleading, we'll fix this.

We haven't reached a point for a v1.0, we're still in early development phase. But if you want to try it out and even contribute feel free to use our dev nuget feed.

https://pkgs.dev.azure.com/uno-platform/1dd81cbd-cb35-41de-a570-b0df3571a196/_packaging/unoplatformdev/nuget/v3/index.json
