### ISSUE TITLE
Look into MaterialComponents directly for more complex components

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/Uno.Material#22]
This repo is a binding over iOS's material implementation. It is the base of Xamarin.Forms's visual Material theme.
https://github.com/xamarin/XamarinComponents/tree/master/iOS/MaterialComponents

**Comment by NicolasChampagne** [comment]
My investigation results: 

[xamarinIosMaterialComponents.txt](https://github.com/unoplatform/Uno.Material/files/4610056/xamarinIosMaterialComponents.txt)

@MatFillion
