### ISSUE TITLE
[WASM][iOS][NavigationView] Back button not visible 

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Material#325]
## Current behavior

![WASM Back button](https://user-images.githubusercontent.com/49959074/88950642-e9d68700-d262-11ea-951d-4b8612d91a3a.png)

## Expected behavior

![UWP Back button](https://user-images.githubusercontent.com/49959074/88950650-ecd17780-d262-11ea-8125-8bcf815bbd6f.png)

## How to reproduce it (as minimally and precisely as possible)

1. Launch app
2. Open NavigationView
3. Notice that back button is not visible (user can still click button and hover over state is still present)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [x] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by MatFillion** [comment]
Was fixed by https://github.com/unoplatform/uno/pull/3775
