### ISSUE TITLE
Checkbox hit-zone should only be the check zone not the label

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/Uno.Material#388]
## Current behavior

Pressing the Label of the checkbox activates the switch

## Expected behavior

Only pressing the checkbox should trigger the check

## How to reproduce it (as minimally and precisely as possible)

Click on the label and notice the textbox is triggered

## Environment

Not relevant

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] UWP
- [ ] MacOS

**Comment by MaximeDion-Work** [comment]
Tried setting IsHitTestVisible="False" on label and removed the tranparent background on root grid, but it's not working on iOS, Android and WASM.
https://github.com/unoplatform/Uno.Material/pull/389/files

**Comment by Xiaoy312** [comment]
This is the correct behavior for uwp. The content is part of the checkbox.
If you need a label that doesnt interact with the checkbox, it should be added separately:
```xml
<StackPanel Orientation="Horizonatal>
    <CheckBox />
    <TextBlock Text="Label" />
```
