### ISSUE TITLE
SolidColorBrushes specified with an opacity, does not work with Android ThumbTint and TrackTint and Wasm Ellipse Fill

### ISSUE THREAD

**Issue by NicolasChampagne** [unoplatform/Uno.Material#41]
## Current behavior
Color is applied without opacity value.

## Expected behavior
The color is properly applied with opacity value.

## How to reproduce it (as minimally and precisely as possible)
- Add a SolidColorBrush that has an opacity value to a BindableSwitchCompat thumb or track tint color.
- Add a SolidColorBrush that has an opacity value to an Ellipses fill in Wasm.

## Environment

Nuget Package:
Latest
Package Version(s):
Latest
Affected platform(s):

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] UWP

**Comment by Xiaoy312** [comment]
https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Controls/BindableSwitchCompat.Android.cs#L79
It is missing a SetAlpha on ThumbTint and TrackTint.

**Comment by NicolasChampagne** [comment]
Thanks @Xiaoy312 

> https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Controls/BindableSwitchCompat.Android.cs#L79
> It is missing a SetAlpha on ThumbTint and TrackTint.
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/132453438/7fcbaf80-9f86-11e9-9d5c-1feea63c9a2e"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[unoplatform/uno](https://github.com/unoplatform/uno)**Build Mobile, Desktop and WebAssembly apps with C# and XAML. Today. Open source and professionally supported. - unoplatform/uno
