### ISSUE TITLE
Q: Where should Uno.Material be installed?

### ISSUE THREAD

**Issue by kotx** [unoplatform/Uno.Material#431]
Should Uno.Material be installed in the UWP project only? Should it be installed in all the projects on Uno (Droid, macOS, Gtk, etc.)?

**Comment by jeromelaban** [comment]
@kotx each project has its own set of dependencies, and the Uno.Material package is no different that the other packages. You'll need to install it in all projects of the solution.

If you have additional questions on the use of the Uno.Material package, could you post intead to https://stackoverflow.com/questions/tagged/uno-platform ? Other users would benefit from this.

Thanks!

**Comment by kotx** [comment]
Thanks.
