### ISSUE TITLE
Implement ElevatedView and Elevation extension on UWP

### ISSUE THREAD

**Issue by MatFillion** [unoplatform/Uno.Material#50]
## What would you like to be added:
ElevatedView and elevation extension compile right now but don't display any shadow.
## Why is this needed:
To look the same on all platforms
## For which Platform:

- [x] UWP

## Anything else we need to know?
The contribution would need to be in Uno directly

**Comment by MatFillion** [comment]
It would probably be something like themeshadow?
https://docs.microsoft.com/en-us/windows/uwp/design/layout/depth-shadow

**Comment by Massimo37** [comment]
@MatFillion  Why is this part of Material and not in Uno ?

**Comment by MatFillion** [comment]
This is why it's required, but the pr needs to be done in uno

**Comment by NicolasChampagne** [comment]
Other notes. ElevatedView inside a splitview causes abnormal and funky rectangular shadows (android/ios)
