### ISSUE TITLE
ComboBox, Placeholder not showing up on iOS and Android

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/Uno.Material#52]
## Current behavior

Placeholder text not showing up on iOS and Android
![image](https://user-images.githubusercontent.com/64613932/81694400-462dc580-942f-11ea-83f6-f3cfff643cc6.png)

## Expected behavior

Placeholder text shows up on iOS and Android like on UWP

## How to reproduce it (as minimally and precisely as possible)

Use combo box with placeholder text

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] UWP

**Comment by XiaotianNetlift** [comment]
https://github.com/unoplatform/Uno.Material/blob/master/src/library/Uno.Material/Styles/Controls/ComboBox.xaml#L333
^ this shouldnt be nested, it works for uwp, but not on xamarin
^ try to put them side-by-sidy
