### ISSUE TITLE
[Android][TextBox] Unable to scroll page when TextBox is in focus

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Material#86]
## Current behavior

Unable to scroll page when TextBox is in focus.

![Uno Material Android TextBox scrolling](https://user-images.githubusercontent.com/49959074/83070136-07a42780-a039-11ea-87b1-30c419d54669.gif)

## Expected behavior

User should be able to scroll the page to access content even if a TextBox is in focus

## How to reproduce it (as minimally and precisely as possible)

1. Launch app
2. Open burger menu
3. Select TextBox
4. Put focus on first or second TextBox
5. Notice that keyboard appears and hides some other content, user is unable to scroll down to access content

## Environment

Nuget Package:
Uno.UI 2.2.0-feature.styles-compat.201

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] UWP

**Comment by Massimo37** [comment]
Fixed. @StewartPolsky to review.

**Comment by StewartPolsky** [comment]
Fix verified
