### ISSUE TITLE
[Android][BottomBarNavigation] BottomBarNavigation is not visible. Can still select different sections

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Material#98]
## Current behavior

![BBN not visible](https://user-images.githubusercontent.com/49959074/83427134-3ede5400-a3fe-11ea-84c2-72853b488817.png)

## Expected behavior

BottomNavigationBar should be visible

## How to reproduce it (as minimally and precisely as possible)

1. Launch app
2. Open burger menu
3. Select BottomBarNavigation
4. Notice that BottomBarNavigation is not visible

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] UWP

## Anything else we need to know?

Issue is present in both light and dark theme. If user taps where any of the bottom sections should be, page does correctly change

**Comment by Massimo37** [comment]
Fixed with latest.

**Comment by StewartPolsky** [comment]
Verified fixed with latest
